spring:
  application:
    name: sqlp-platform
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sqlp}
    username: ${DB_USERNAME:sqlp}
    password: ${DB_PASSWORD:sqlp}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
